export const products = [
    {
        img: 'https://images.pexels.co875465/pexel75465.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load&fit=crop',
        title: 'Food, Snacks & Drinks',
        subtitle: "@ Service Provider",
        inCart: true,
        isFav: true,
        price: 2999,
        body: "Product Details that I can't think of any presently, but sooner or later I will be adding the project details analysing the customer's/provider's need. Product Details that I can't think of any presently, but sooner or later I will be adding the project details analysing the customer's/provider's need. ",
    },
    {
        img: 'https://images.pexels.co875465/pexel75465.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load&fit=crop',
        title: 'Household Services',
        subtitle: "@ Service Provider",
        inCart: true,
        isFav: true,
        price: 2999,
        body: "Product Details that I can't think of any presently, but sooner or later I will be adding the project details analysing the customer's/provider's need. Product Details that I can't think of any presently, but sooner or later I will be adding the project details analysing the customer's/provider's need. ",
    },
    {
        img: 'https://images.pexels.co875465/pexel75465.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load&fit=crop',
        title: 'Toys & Games',
        subtitle: "@ Service Provider",
        inCart: true,
        isFav: true,
        price: 2999,
        body: "Product Details that I can't think of any presently, but sooner or later I will be adding the project details analysing the customer's/provider's need. Product Details that I can't think of any presently, but sooner or later I will be adding the project details analysing the customer's/provider's need. ",
    },
    {
        img: 'https://images.pexels.co875465/pexel75465.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load&fit=crop',
        title: 'Mobiles, Laptops & other electronics ',
        subtitle: "@ Service Provider",
        inCart: true,
        isFav: true,
        price: 2999,
        body: "Product Details that I can't think of any presently, but sooner or later I will be adding the project details analysing the customer's/provider's need. Product Details that I can't think of any presently, but sooner or later I will be adding the project details analysing the customer's/provider's need. ",
    },
    {
        img: 'https://images.pexels.co875465/pexel75465.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load&fit=crop',
        title: 'Beauty & Personal Care',
        subtitle: "@ Service Provider",
        inCart: true,
        isFav: true,
        price: 2999,
        body: "Product Details that I can't think of any presently, but sooner or later I will be adding the project details analysing the customer's/provider's need. Product Details that I can't think of any presently, but sooner or later I will be adding the project details analysing the customer's/provider's need. ",
    },
    {
        img: 'https://images.pexels.co875465/pexel75465.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load&fit=crop',
        title: 'Clothing, Shoes & Accessories',
        subtitle: "@ Service Provider",
        inCart: true,
        isFav: true,
        price: 2999,
        body: "Product Details that I can't think of any presently, but sooner or later I will be adding the project details analysing the customer's/provider's need. Product Details that I can't think of any presently, but sooner or later I will be adding the project details analysing the customer's/provider's need. ",
    },
    {
        img: 'https://images.pexels.co875465/pexel75465.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load&fit=crop',
        title: 'Sports & Outdoors',
        subtitle: "@ Service Provider",
        inCart: true,
        isFav: true,
        price: 2999,
        body: "Product Details that I can't think of any presently, but sooner or later I will be adding the project details analysing the customer's/provider's need. Product Details that I can't think of any presently, but sooner or later I will be adding the project details analysing the customer's/provider's need. ",
    },
    {
        img: 'https://images.unsplash.co0222094114-d054a817e56b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwhttps://images.pexels.co875465/pexel75465.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load&fit=crop',
        title: 'Appliances',
        subtitle: "@ Service Provider",
        inCart: true,
        isFav: true,
        price: 2999,
        body: "Product Details that I can't think of any presently, but sooner or later I will be adding the project details analysing the customer's/provider's need. Product Details that I can't think of any presently, but sooner or later I will be adding the project details analysing the customer's/provider's need. ",
    }
];

export const suggestions = products.map(product => product.title);

export const images = products.map(product => product.img);

export const currencies = {
    "INR": "Indian Rupee"
};

export const allCurrencies = {
    "USD": "US Dollar",
    "CAD": "Canadian Dollar",
    "EUR": "Euro",
    "AED": "United Arab Emirates Dirham",
    "AFN": "Afghan Afghani",
    "ALL": "Albanian Lek",
    "AMD": "Armenian Dram",
    "ARS": "Argentine Peso",
    "AUD": "Australian Dollar",
    "AZN": "Azerbaijani Manat",
    "BAM": "Bosnia-Herzegovina Convertible Mark",
    "BDT": "Bangladeshi Taka",
    "BGN": "Bulgarian Lev",
    "BHD": "Bahraini Dinar",
    "BIF": "Burundian Franc",
    "BND": "Brunei Dollar",
    "BOB": "Bolivian Boliviano",
    "BRL": "Brazilian Real",
    "BWP": "Botswanan Pula",
    "BYN": "Belarusian Ruble",
    "BZD": "Belize Dollar",
    "CDF": "Congolese Franc",
    "CHF": "Swiss Franc",
    "CLP": "Chilean Peso",
    "CNY": "Chinese Yuan",
    "COP": "Colombian Peso",
    "CRC": "Costa Rican Colón",
    "CVE": "Cape Verdean Escudo",
    "CZK": "Czech Republic Koruna",
    "DJF": "Djiboutian Franc",
    "DKK": "Danish Krone",
    "DOP": "Dominican Peso",
    "DZD": "Algerian Dinar",
    "EEK": "Estonian Kroon",
    "EGP": "Egyptian Pound",
    "ERN": "Eritrean Nakfa",
    "ETB": "Ethiopian Birr",
    "GBP": "British Pound Sterling",
    "GEL": "Georgian Lari",
    "GHS": "Ghanaian Cedi",
    "GNF": "Guinean Franc",
    "GTQ": "Guatemalan Quetzal",
    "HKD": "Hong Kong Dollar",
    "HNL": "Honduran Lempira",
    "HRK": "Croatian Kuna",
    "HUF": "Hungarian Forint",
    "IDR": "Indonesian Rupiah",
    "ILS": "Israeli New Sheqel",
    "INR": "Indian Rupee",
    "IQD": "Iraqi Dinar",
    "IRR": "Iranian Rial",
    "ISK": "Icelandic Króna",
    "JMD": "Jamaican Dollar",
    "JOD": "Jordanian Dinar",
    "JPY": "Japanese Yen",
    "KES": "Kenyan Shilling",
    "KHR": "Cambodian Riel",
    "KMF": "Comorian Franc",
    "KRW": "South Korean Won",
    "KWD": "Kuwaiti Dinar",
    "KZT": "Kazakhstani Tenge",
    "LBP": "Lebanese Pound",
    "LKR": "Sri Lankan Rupee",
    "LTL": "Lithuanian Litas",
    "LVL": "Latvian Lats",
    "LYD": "Libyan Dinar",
    "MAD": "Moroccan Dirham",
    "MDL": "Moldovan Leu",
    "MGA": "Malagasy Ariary",
    "MKD": "Macedonian Denar",
    "MMK": "Myanma Kyat",
    "MOP": "Macanese Pataca",
    "MUR": "Mauritian Rupee",
    "MXN": "Mexican Peso",
    "MYR": "Malaysian Ringgit",
    "MZN": "Mozambican Metical",
    "NAD": "Namibian Dollar",
    "NGN": "Nigerian Naira",
    "NIO": "Nicaraguan Córdoba",
    "NOK": "Norwegian Krone",
    "NPR": "Nepalese Rupee",
    "NZD": "New Zealand Dollar",
    "OMR": "Omani Rial",
    "PAB": "Panamanian Balboa",
    "PEN": "Peruvian Nuevo Sol",
    "PHP": "Philippine Peso",
    "PKR": "Pakistani Rupee",
    "PLN": "Polish Zloty",
    "PYG": "Paraguayan Guarani",
    "QAR": "Qatari Rial",
    "RON": "Romanian Leu",
    "RSD": "Serbian Dinar",
    "RUB": "Russian Ruble",
    "RWF": "Rwandan Franc",
    "SAR": "Saudi Riyal",
    "SDG": "Sudanese Pound",
    "SEK": "Swedish Krona",
    "SGD": "Singapore Dollar",
    "SOS": "Somali Shilling",
    "SYP": "Syrian Pound",
    "THB": "Thai Baht",
    "TND": "Tunisian Dinar",
    "TOP": "Tongan Paʻanga",
    "TRY": "Turkish Lira",
    "TTD": "Trinidad and Tobago Dollar",
    "TWD": "New Taiwan Dollar",
    "TZS": "Tanzanian Shilling",
    "UAH": "Ukrainian Hryvnia",
    "UGX": "Ugandan Shilling",
    "UYU": "Uruguayan Peso",
    "UZS": "Uzbekistan Som",
    "VEF": "Venezuelan Bolívar",
    "VND": "Vietnamese Dong",
    "XAF": "CFA Franc BEAC",
    "XOF": "CFA Franc BCEAO",
    "YER": "Yemeni Rial",
    "ZAR": "South African Rand",
    "ZMK": "Zambian Kwacha",
    "ZWL": "Zimbabwean Dollar"
};

export const categories = [
    { title: "Food and Beverages", desc: "Groceries, Snacks, Beverages, Gourmet Food, etc.", photo: "/images/categories/Food and Beverages.jpg", cols: 2, rows: 2},
    { title: "Electronics", desc: "Smartphones, Laptops, Cameras, Televisions, etc.", photo: "/images/categories/Electronics.jpg", cols: 1, rows: 1},
    { title: "Home and Garden", desc: "Furniture, Home Decor, Appliances, Gardening Tools, etc.", photo: "/images/categories/Home and Garden.jpg", cols: 1, rows: 1},
    { title: "Health and Beauty", desc: "Skincare Products, Makeup, Haircare Products, Personal Care Items, etc.", photo: "/images/categories/Health and Beauty.jpg", cols: 1, rows: 1},
    { title: "Sports and Outdoors", desc: "Bicycles, Camping Gear, Fitness Equipment, Sports Accessories, etc.", photo: "/images/categories/Sports and Outdoors.jpg", cols: 1, rows: 1},
    { title: "Toys and Games", desc: "Board Games, Puzzles, Action Figures, Dolls, etc.", photo: "/images/categories/Toys and Games.jpg", cols: 1, rows: 1},
    { title: "Services", desc: "Home Repairs, Domestic Help, Painting, Salon, Massage, etc.", photo: "/images/categories/Services.jpg", cols: 1, rows: 1},
    { title: "Clothing and Accessories", desc: "Clothing, Shoes, Jewellery, Bags, etc.", photo: "/images/categories/Clothing and Accessories.jpg", cols: 2, rows: 2},
    { title: "Books and Media", desc: "Books, E-books, Audiobooks, Movies, Music, Video Games, etc.", photo: "/images/categories/Books and Media.jpg", cols: 1, rows: 1},
    { title: "Office and School Supplies", desc: "Stationery, Office Equipment, School Supplies, Art Supplies, etc.", photo: "/images/categories/Office and School Supplies.jpg", cols: 1, rows: 1},
];